package ch.usi.inf.bsc.sa4.lab02spring.controller.dto;

import java.util.UUID;

/**
 * Represents a generic AI response data transfer object (DTO) containing metadata and content of an
 * AI-generated answer.
 */
public abstract class AiAbstractResponseDTO {

  /** The unique identifier of the AI response. */
  private final UUID aiResponseDid;

  /** Indicates whether this response is publicly visible. */
  private final boolean isPublic;

  /** The overall rating score assigned to this response. */
  private final int rating;

  /** The rating provided by the user for this response. */
  private final Integer userRating;

  /** The textual answer generated by the AI. */
  private final String answer;

  /** The type of question this response corresponds to. */
  private String questionType;

  /**
   * Creates a new AI response DTO with the specified identifier, visibility, rating, user rating,
   * and answer content.
   *
   * @param aiResponseDid the unique identifier of the AI response
   * @param isPublic true if this response should be publicly visible; false otherwise
   * @param rating the overall rating score assigned to this response
   * @param userRating the rating provided by the user (may be null if not yet rated)
   * @param answer the textual content of the AI-generated answer
   */
  protected AiAbstractResponseDTO(
      UUID aiResponseDid, boolean isPublic, int rating, Integer userRating, String answer) {
    this.aiResponseDid = aiResponseDid;
    this.isPublic = isPublic;
    this.rating = rating;
    this.userRating = userRating;
    this.answer = answer;
  }

  /**
   * Returns the unique identifier of this AI response.
   *
   * @return the UUID corresponding to this AI response
   */
  public UUID getAiResponseDid() {
    return aiResponseDid;
  }

  /**
   * Returns the overall rating score that has been assigned to this AI response.
   *
   * @return the rating score as an integer
   */
  public boolean isPublic() {
    return isPublic;
  }

  /**
   * Returns the overall rating score that has been assigned to this AI response.
   *
   * @return the rating score as an integer
   */
  public int getRating() {
    return rating;
  }

  /**
   * Returns the rating provided by the user for this response.
   *
   * @return the user’s rating, or {@code null} if the user has not rated yet
   */
  public Integer getUserRating() {
    return userRating;
  }

  /**
   * Returns the textual answer generated by the AI.
   *
   * @return the AI-generated answer string
   */
  public String getAnswer() {
    return answer;
  }

  /**
   * Returns the type of question this response corresponds to.
   *
   * @return a string representing the question type, or {@code null} if not set
   */
  public String getQuestionType() {
    return questionType;
  }

  /**
   * Sets the type of question for this AI response.
   *
   * @param questionType a string indicating the question type
   */
  public void setQuestionType(String questionType) {
    this.questionType = questionType;
  }
}
