package ch.usi.inf.bsc.sa4.lab02spring.controller.dto;

import ch.usi.inf.bsc.sa4.lab02spring.model.AIMaterialResponse;

/**
 * Data Transfer Object (DTO) representing a response generated by an AI system. This record
 * encapsulates the essential attributes related to an AI-generated response These fields enable
 * efficient exchange of data about AI responses between layers of the application.
 */
public class AiMaterialResponseDTO extends AiAbstractResponseDTO {

  /** The question text associated with this AI-generated response. */
  private final String questionText;

  /** The highlighted text associated with this AI-generated response. */
  private final String highlightedText;

  /**
   * Constructs an {@code AiMaterialResponseDTO} from the given {@link AIMaterialResponse} and user
   * rating.
   *
   * @param materialResponse the {@link AIMaterialResponse} entity containing AI-generated response
   *     data
   * @param userRating the rating provided by the user for this response
   */
  public AiMaterialResponseDTO(AIMaterialResponse materialResponse, Integer userRating) {
    super(
        materialResponse.getAiResponseDID(),
        materialResponse.getIsPublic(),
        materialResponse.getRate(),
        userRating,
        materialResponse.getAiAnswer());
    this.questionText = materialResponse.getQuestionText();
    this.highlightedText = materialResponse.getHighlightedText();
    setQuestionType("Markdown Question");
  }

  /**
   * Returns the question text associated with this AI-generated response.
   *
   * @return the question text
   */
  public String getQuestionText() {
    return questionText;
  }

  /**
   * Returns the highlighted text associated with this AI-generated response.
   *
   * @return the highlighted text
   */
  public String getHighlightedText() {
    return highlightedText;
  }
}
