package ch.usi.inf.bsc.sa4.lab02spring.controller.dto;

/**
 * Data Transfer Object (DTO) representing a response comparison between a user and AI.
 *
 * <p>Contains the username of the respondent, the answer provided by the user, and the answer
 * generated by the AI for comparison or evaluation purposes.
 *
 * @param userName the name or identifier of the user who gave the answer
 * @param userAnswer the answer submitted by the user
 * @param aiAnswer the answer generated by the AI for the same question
 */
public record SHAResponseDTO(String userName, String userAnswer, String aiAnswer) {}
