/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ExerciseComponent: typeof import('./components/ExerciseComponent.vue')['default']
    HeaderComponent: typeof import('./components/HeaderComponent.vue')['default']
    MaterialComponent: typeof import('./components/MaterialComponent.vue')['default']
    ResultSearchBar: typeof import('./components/ResultSearchBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    ThemeToggleComponent: typeof import('./components/ThemeToggleComponent.vue')['default']
  }
}
