package ch.usi.inf.bsc.sa4.lab02spring.model;

import ch.usi.inf.bsc.sa4.lab02spring.controller.dto.AiAbstractResponseDTO;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Inheritance;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import static jakarta.persistence.CascadeType.ALL;
import static jakarta.persistence.FetchType.LAZY;
import static jakarta.persistence.GenerationType.TABLE;
import static jakarta.persistence.InheritanceType.JOINED;

/**
 * Abstract class for AI response.
 *
 * <p>This entity represents the common properties and relationships of all AI response types. It is
 * mapped to the "aiResponse" table in the database and uses the {@code JOINED} inheritance
 * strategy, meaning that subclasses will have their own tables that share a primary key with this
 * table.
 */

/**
 * Abstract base class for all AI response entities.
 *
 * <p>Maps to the database table {@code aiResponse} and employs the JOINED inheritance strategy,
 * storing common fields in this table while subclass‐specific data resides in separate tables. The
 * primary key is generated via the TABLE strategy for portability across databases. Each instance
 * also has a globally unique DID (UUID) for external reference.
 */
@Entity
@Inheritance(strategy = JOINED)
@Table(name = "aiResponse")
public abstract class AbstractAIResponse {

  /**
   * Auto‐generated surrogate key for internal identity. Generated using the TABLE strategy to
   * ensure compatibility across JPA providers.
   */
  @Id
  @GeneratedValue(strategy = TABLE)
  @Column(name = "aiResponseId")
  protected long aiResponseId;

  /**
   * Globally unique decentralized identifier (DID) for external reference. Marked unique and
   * non‐updatable to maintain immutability.
   */
  @Column(name = "aiResponseDID", unique = true, updatable = false)
  protected UUID aiResponseDID;

  /** Flag indicating whether the response is publicly visible. */
  @Column(name = "public", nullable = false)
  protected boolean isPublic;

  /**
   * The AI‐generated answer text. Column length extended to accommodate long responses.
   */
  @Column(name = "aiAnswer", nullable = false, length = 10000)
  protected String aiAnswer;

  /** Numeric rating of the response (e.g., user up/down votes). */
  @Column(name = "rate", nullable = false)
  protected int rate;

  /**
   * Owning student who generated the AI question. Fetched lazily to avoid unnecessary joins.
   */
  @ManyToOne(fetch = LAZY)
  @JoinColumn(name = "id")
  protected Student owner;

  /**
   * Collection of student votes associated with this response. Cascade all operations and remove
   * orphan votes.
   */
  @OneToMany(mappedBy = "aiResponseId", cascade = ALL, orphanRemoval = true)
  protected Set<AIVoteStudent> votes = new HashSet<>();

  /** Protected no‐arg constructor required by JPA. */
  protected AbstractAIResponse() {}

  /**
   * Constructs a new AI response with the given visibility, question, answer, and owner. A new UUID
   * is generated for the DID, and the initial rate is set to zero.
   *
   * @param isPublic whether the response is publicly visible
   * @param aiAnswer the answer generated by the AI
   * @param owner the {@link Student} who created the response
   */
  protected AbstractAIResponse(Boolean isPublic, String aiAnswer, Student owner) {
    this.aiResponseDID = UUID.randomUUID();
    this.isPublic = isPublic;
    this.aiAnswer = aiAnswer;
    this.owner = owner;
    this.rate = 0;
  }

  /**
   * Returns the primary key identifier of the ai response.
   *
   * @return the internal database ID of this AI response
   */
  public long getAiResponseId() {
    return aiResponseId;
  }

  /**
   * Returns the unique decentralized identifier (DID) of the answer.
   *
   * @return the globally unique decentralized identifier (UUID) of this AI response
   */
  public UUID getAiResponseDID() {
    return this.aiResponseDID;
  }

  /**
   * Sets a new decentralized identifier (UUID) for this response.
   *
   * @param aiResponseDID the new UUID to assign
   */
  public void setAIResponseDID(UUID aiResponseDID) {
    this.aiResponseDID = aiResponseDID;
  }

  /**
   * Returns the public flag of the answer.
   *
   * @return {@code true} if this response is publicly visible
   */
  public boolean getIsPublic() {
    return isPublic;
  }

  /**
   * Toggles the public visibility flag of this response.
   *
   * @param isPublic {@code true} to make the response public; {@code false} otherwise
   */
  public void setIsPublic(boolean isPublic) {
    this.isPublic = isPublic;
  }

  /**
   * Returns the AI-generated answer.
   *
   * @return the AI‐generated answer text
   */
  public String getAiAnswer() {
    return aiAnswer;
  }

  /**
   * Updates the AI‐generated answer text.
   *
   * @param aiAnswer the new AI answer text
   */
  public void setAiAnswer(String aiAnswer) {
    this.aiAnswer = aiAnswer;
  }

  /**
   * Returns the numeric rating of this response.
   *
   * @return the numeric rating of this response
   */
  public int getRate() {
    return rate;
  }

  /**
   * Updates the numeric rating of this response.
   *
   * @param rate the new rating value
   */
  public void setRate(int rate) {
    this.rate = rate;
  }

  /**
   * Returns the {@link Student} who owns this response.
   *
   * @return the {@link Student} who owns this response
   */
  public Student getOwner() {
    return owner;
  }

  /**
   * Sets the {@link Student} owner of this response.
   *
   * @param owner the new owner
   */
  public void setOwner(Student owner) {
    this.owner = owner;
  }

  /**
   * Converts the current object into an {@link AiAbstractResponseDTO}, incorporating the provided
   * user rating.
   *
   * <p>This method is intended to be implemented by subclasses to transform their specific data
   * into a standardized {@code AiAbstractResponseDTO} format, which may be used for data transfer
   * operations such as API responses.
   *
   * @param userRating the rating provided by the user, which can be {@code null} if no rating is
   *     available
   * @return an instance of {@code AiAbstractResponseDTO} representing the current object's data
   */
  public abstract AiAbstractResponseDTO toDTO(Integer userRating);
}
