package ch.usi.inf.bsc.sa4.lab02spring.model;

import static jakarta.persistence.FetchType.EAGER;

import ch.usi.inf.bsc.sa4.lab02spring.controller.dto.AiAbstractResponseDTO;
import ch.usi.inf.bsc.sa4.lab02spring.controller.dto.AiExerciseResponseDTO;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import java.util.UUID;

/**
 * JPA entity representing an AI-generated response to an exercise question.
 *
 * <p>Extends {@code AbstractAIResponse} to include the user’s submitted answer, the original
 * question, and the associated persisted Answer entity.
 */
@Entity
public class AIExerciseResponse extends AbstractAIResponse {

  /** The answer provided by the user. */
  @Column(name = "userAnswer", nullable = false)
  protected String userAnswer;

  /** The question to which this AI response pertains. */
  @ManyToOne(fetch = EAGER)
  @JoinColumn(name = "questionID", nullable = false)
  protected AbstractQuestion question;

  /** The {@link Answer} associated with this response. */
  @ManyToOne(fetch = EAGER)
  @JoinColumn(name = "answerID")
  private Answer answer;

  /** Protected no‐arg constructor required by JPA. */
  protected AIExerciseResponse() {}

  /**
   * Constructs a new AI exercise response.
   *
   * @param isPublic whether the response is publicly visible
   * @param aiAnswer the answer generated by the AI
   * @param owner the student who owns this response
   * @param userAnswer the answer submitted by the user
   * @param answer the persisted Answer entity matching the user’s submission
   * @param question the question being answered
   */
  public AIExerciseResponse(
      Boolean isPublic,
      String aiAnswer,
      Student owner,
      String userAnswer,
      Answer answer,
      AbstractQuestion question) {
    super(isPublic, aiAnswer, owner);
    this.userAnswer = userAnswer;
    this.answer = answer;
    this.question = question;
  }

  /**
   * Constructs a new AI exercise response with a predefined DID.
   *
   * @param isPublic whether the response is publicly visible
   * @param aiAnswer the answer generated by the AI
   * @param owner the student who owns this response
   * @param userAnswer the answer submitted by the user
   * @param answer the persisted Answer entity matching the user’s submission
   * @param question the question being answered
   * @param did the UUID to assign as this response’s DID
   */
  public AIExerciseResponse(
      Boolean isPublic,
      String aiAnswer,
      Student owner,
      String userAnswer,
      Answer answer,
      AbstractQuestion question,
      UUID did) {
    super(isPublic, aiAnswer, owner);
    this.aiResponseDID = did;
    this.userAnswer = userAnswer;
    this.answer = answer;
    this.question = question;
  }

  /**
   * Constructs an exercise response directly from an AI evaluation.
   *
   * @param eval the AI evaluation from which to build this response
   */
  public AIExerciseResponse(AIEvaluation eval) {
    super(false, eval.getAiReasoning(), eval.getOwner());
    this.userAnswer = eval.getAnswer().getAnswerContent();
    this.answer = eval.getAnswer();
    this.question = eval.getQuestion();
  }

  /**
   * Returns the answer of the user
   *
   * @return the answer of the user
   */
  public String getUserAnswer() {
    return userAnswer;
  }

  /**
   * sets the answer of the user
   *
   * @param userAnswer the new answer string
   */
  public void setUserAnswer(String userAnswer) {
    this.userAnswer = userAnswer;
  }

  /**
   * Returns the {@link Answer} associated with this response.
   *
   * @return the associated {@link Answer}
   */
  public Answer getAnswer() {
    return answer;
  }

  /**
   * Sets the {@link Answer} associated with this response.
   *
   * @param answer the new {@link Answer} to associate with this response
   */
  public void setAnswer(Answer answer) {
    this.answer = answer;
  }

  /**
   * Converts this entity into a transport DTO, including a user rating.
   *
   * @param rate the user’s rating for this response
   * @return an {@code AiAbstractResponseDTO} representing this response
   */
  @Override
  public AiAbstractResponseDTO toDTO(Integer rate) {
    return new AiExerciseResponseDTO(this, rate);
  }
}
